Dotneteer/kliveide

- packages/kliveide-emu/src/native/api/memory-map.ts
- packages/kliveide-emu/src/native/memory-map.wat
- packages/kliveide-emu/src/native/z80/z80-bit-ops.wat
- packages/kliveide-emu/src/native/z80/z80-extended-ops.wat
- packages/kliveide-emu/src/native/z80/z80-indexed-bit-ops.wat
- packages/kliveide-emu/src/native/z80/z80-indexed-ops.wat
- packages/kliveide-emu/src/native/z80/z80-standard-ops.wat
- packages/kliveide-emu/src/native/z80/z80.wat
- packages/kliveide-emu/src/native/zx-spectrum-48.wat
- packages/kliveide-emu/src/renderer/spectrum/SpectrumEngine.ts
- packages/kliveide-emu/test/z80/flags.test.ts
- packages/kliveide-emu/test/z80/standard-ops-00-3f.test.ts
- packages/kliveide-emu/test/z80/standard-ops-80-bf.test.ts
The CPU's instructions are zexall compliant except `BIT N,(HL)`
> refactor: review Z80 implementation and make it zexall compliant

- packages/kliveide-vsext/package.json
Previously you could set it between 0 and 3.
> fix: allow the ZXB optimization set between 0 and 4.

- packages/kliveide-emu/src/main/cz-88-context.ts
I've replaced the template examples with some real-purpose links to useful information about general use of the Z88, how to develop software for it, and general information and software available for it.
> Added Z88-specific items in Help menu

- packages/kliveide-emu/src/main/cz-88-context.ts
I've added a new menu item for Z88 specific menu, that is the complete 2nd edition of the BBC Basic Reference Guide for Z88, 2nd edition.
> Added z88-specific menu item to online BBC Basic Ref. Guide

- packages/kliveide-vsext/src/zxblang/compiler/zxb-runner.ts
-- Zxbc Executable Path: now can use spaces in path
Verified use spaces, / ,or \, for paths:
Emulator Executable Path and Zxbc Executable Path
> fixed settings paths:

- package.json
- src/core/main/zx-spectrum-context.ts
- src/core/messaging/message-types.ts
- src/emu/emu-message-processor.ts
- src/emu/emu-renderer.tsx
- src/main/app/app-menu.ts
- src/modules/core/memory-helpers.ts
- src/modules/core/vm-engine-service.ts
- src/modules/vm-zx-spectrum/ZxSpectrumCoreBase.ts
- src/modules/vm-zx-spectrum/wa-memory-map.ts
- src/test/z80/import-object.ts
- src/wats/sp128-core/sp128.wats
- src/wats/sp48-core/sp48.wats
- src/wats/spectrum-core/machine.wats
- src/wats/spectrum-core/sound-device.wats
- src/wats/spectrum-core/tape-device.wats
- src/wats/spp3e-core/spp3e.wats
Greetings, @Dotneteer. 👋  I liked your IDE pretty much, but couldn't figure out how to materialize the compiled machine code. After a few days of research I came with this approach that enables IDE users to export the compiled ZX Spectrum programs as tape files.
The feature is meant to be as follows:
First, user prepares the code/data RAM layout by either compiling the project sources or by entering them manually while interacting with virtual machine. Next, user saves the desired parts on tape. After, the saved tape buffer is exported into TZX file via 'Machine->Export SAVEd tape data' menu option.
Here it is a [new_tape.zip](https://github.com/Dotneteer/kliveide/files/12167103/new_tape.zip) file obtained the way described above. The tape is comprised of:
1. 'p' - a little program, load …
> Feature: tape export

- docs/_posts/documents/2021-01-01-directives.md
- docs/_posts/documents/2021-01-01-expressions.md
- docs/_posts/documents/2021-01-01-how-assembler-works.md
- docs/_posts/documents/2021-01-01-labels-and-symbols.md
- docs/_posts/documents/2021-01-01-language-structure.md
- docs/_posts/documents/2021-01-01-macros.md
- docs/_posts/documents/2021-01-01-main-features.md
- docs/_posts/documents/2021-01-01-pragmas.md
- docs/_posts/documents/2021-01-01-statements.md
- docs/_posts/documents/2021-01-01-structs.md
- docs/_posts/documents/2021-01-01-z80-instructions.md
- docs/_posts/getting-started/2020-08-01-use-the-emulator.md
- docs/_posts/spectrum/2019-01-01-basic-appc1.md
- docs/_posts/spectrum/2019-01-01-basic-appc2.md
- docs/_posts/spectrum/2019-01-01-basic-ch10.md
- docs/_posts/spectrum/2019-01-01-basic-ch13.md
- docs/_posts/spectrum/2019-01-01-basic-ch14.md
- docs/_posts/spectrum/2019-01-01-basic-ch15.md
- docs/_posts/spectrum/2019-01-01-basic-ch16.md
- docs/_posts/spectrum/2019-01-01-basic-ch18.md
- docs/_posts/spectrum/2019-01-01-basic-ch20.md
- docs/_posts/spectrum/2019-01-01-basic-ch23.md
- docs/_posts/spectrum/2019-01-01-basic-ch24.md
- docs/_posts/spectrum/2019-01-01-basic-ch25.md
- docs/_posts/spectrum/2019-01-01-basic-ch3.md
- docs/_posts/spectrum/2019-01-01-basic-ch4.md
- docs/_posts/spectrum/2019-01-01-basic-ch5.md
- docs/_posts/spectrum/2019-01-01-basic-ch7.md
- docs/_posts/spectrum/2019-01-01-basic-ch9.md
I got tired eyeballing everything in order to find some typos beyond what I have noticed while was reading through topics of interest; So I have put the whole markdown content through a utility called [_aspell_](http://aspell.net/). This also revealed a few OCR errors along the way.
> Minor typos fixed across GitHub pages body of content.

- src/renderer/controls/VirtualizedList.tsx
IDE Command output is made to scroll reliably to bottom upon the commands output buffer is changed.
Because of delayed update of a scroller's height scrollToIndex appears to not do its job in this case; but scrolltoOffset does. @Dotneteer, pull and check on macOS machine, please.
> fix: IDE Command pane scrolling bug

- src/main/z80-compiler/assembler.ts
- test/assembler/struct-regression.test.ts
The case is that the struct initialization expression 'eats up' the following label declaration; or vice versa the declared label never makes it into symbols table when preceded with a struct initialization.
The code like this:
```
ld hl,ThisShouldNotFail
SnakeHead: Point2d()
ThisShouldNotFail: .db #55
```
won't compile without this change.
But, after reading [the docs](https://dotneteer.github.io/kliveide/documents/structs#article) one may find this behaviour surprising. 
Well, this one PR I am not too confident about. At least it pass tests successfully.
> fix: an unexpected ERROR Z0605 when initializing a struct

- src/renderer/appIde/project/asmKz80LangaugeProvider.ts
Some directives that start with HEX letter digits were treated as hexadecimal literals by mistake:
Here it is my attempt to work around that.
> Tweak Assembler directives syntax highlight.

- src/main/z80-compiler/assembler.ts
- test/assembler/regression.test.ts
This happened when 'current address' specifier is featured in a directive expression;
I have bumped into it when was doing something similar to:
```
.db Bar & 0xFF
#if ($ >> 8) > ($ & 0xFF)
nop
#endif
Bar:
jp 0
```
What was happening is that `executeParse` method had created the current segment indirectly (through the `ensureSegment`), whereas  `emitCode` method was cleraring the output.segments list without nullifying the current segment's field. This way, due to how the `ensureSegment` method's designed the current code segment wasn't pushed to output segments ever since.  And finally some of the fixups (those which were created globally, or better module-wise) end up with a negative code segment index, leading us to the “Cannot read property of undefined” error to happen within the …
> Fix the missing output segment during fixup.

- src/renderer/appIde/DocumentPanels/MonacoEditor.tsx
- src/renderer/appIde/commands/DocumentCommands.ts
Path normalization added in order to have uniform path separators when looking for project node.
Without this, for instance clicking a link in the compilation error message won't bring up a document with that particular error on Windows.
> fix: document navigation on Windows.

- src/renderer/appIde/SiteBarPanels/ExplorerPanel.tsx
Recently I have noticed that context menu is not always shown when you click on project tree items. After digging a little it was found that context menu (popper element) position offset is wrong most of the time (when Klive IDE window is not fullscreen or is not on the primary monitor of the multi-monitor system).
This is my workaround for this little issue. I have checked the fix when in various Windows projection modes - seems OK.
> fix: Context menu positioning over the Explorer's panel.

- src/common/messaging/any-to-main.ts
- src/common/messaging/dialog-ids.ts
- src/common/messaging/messages-core.ts
- src/common/state/Action.ts
- src/common/state/ActionTypes.ts
- src/common/state/AppState.ts
- src/common/state/actions.ts
- src/common/state/project-reducer.ts
- src/main/RendererToMainProcessor.ts
- src/main/app-menu.ts
- src/main/directory-content.ts
- src/main/projects.ts
- src/main/settings.ts
- src/renderer/appIde/IdeApp.tsx
- src/renderer/appIde/SiteBarPanels/ExplorerPanel.tsx
- src/renderer/appIde/dialogs/ExcludedProjectItemsDialog.module.scss
- src/renderer/appIde/dialogs/ExcludedProjectItemsDialog.tsx
- src/renderer/appIde/project/project-node.ts
- src/renderer/controls/ContextMenu.module.scss
- src/renderer/controls/ContextMenu.tsx
- src/renderer/controls/Tooltip.tsx
- src/renderer/registry.ts
- src/renderer/theming/dark-theme.ts
- src/renderer/theming/light-theme.ts
- src/renderer/theming/theme.ts
Here we have file tree filtering, so anything unrelated with Klive is shown under the project tree. Given how the project tree is being build I think this is the simplest solution that gets job done.
User is now enabled to exclude any unwanted items from their project:
> Filter out any files unrelated with Klive from project file tree.

- src/main/app-menu.ts
- src/main/index.ts
There were two issues intertwined: first, the menu separators weren't removed after empty sections; and the second, the menu contents dependent of focused windows state could get stale that's because how window focusing works.
@Dotneteer , please check whether it works for you on macOS.
The test cases are like that:
The First
1. Launch Klive
2. Make sure **_IDE window_** is open
3. Focus it
4. Now click 'View' menu item on **_EMU window_**
**What to expect**: the menu won't bring up before the EMU window gets focused. Click the 'View' item on EMU window again to see the menu filled up correctly with its corresponding context.
The Second
1. Launch Klive
2. Make sure both windows are open
3. Unfocus all the windows
4. Now click the 'View' menu item on any of the windows
**What to expect**: …
> Fix the App's main menu weird behaviour.

- src/main/app-menu.ts
Electron does not support window-specific menus on Mac, only application menu. The previous fix works with this patch on Mac.
> fix: menu now works with Mac

- src/main/z80-compiler/assembler.ts
- test/assembler/directive.test.ts
I decided to re-factor my project a little. One of the refactoring steps was to split the code base into smaller files introducing the header guards so to prevent the same code from multiple inclusion. 
This is how I bumped into an issue: includes that found themselves within the supposedly skipped conditional scopes were expanded and parsed. Here's the fix. :)
P.S.: The model pragma is also refrained from being processed when under the non-met conditional. This is how I see it: preprocessing goes before pragmas handling, so no pragma should made it into further compilation steps from skipped conditional blocks.
> Fix: #include inside the scope of non-met #if condition.

- src/main/z80-compiler/assembly-module.ts
- test/assembler/macro-def.test.ts
I thought over this issue after our talk. Indeed, it appeared to be the smallest quirk.
IMO, the fix suggested here provides the most intiutive and straightforward behaviour the user could expect from macros lookup.
> Fix: macro definitions lookup.

- src/common/utils/DelayedJobs.ts
- src/main/index.ts
- src/renderer/abstractions/IProjectService.ts
- src/renderer/appIde/DocumentPanels/MonacoEditor.tsx
- src/renderer/appIde/services/ProjectService.ts
This is a re-factoring attempt as we discussed, including a little update to the recent 'save-on-exit' logic.
I have tested the three cases of how user may quit an application:
- File -> Exit
- Close all windows at the Windows task bar context menu
- Closing the Emu with sysmenu button.
There is the interactive Exit command, which makes the app.quit() call, so let's treat it the same as the File -> Exit case.
> Refactor save file content

- src/renderer/appIde/SiteBarPanels/ExplorerPanel.tsx
- src/renderer/controls/Toolbar.tsx
In addition, 'Refresh' context menu item is added at the root folder tree entry.
> Restrict all the features that don't make sense when the open folder is not a Klive project.

- src/emu/machines/z88/Z88BlinkDevice.ts
- src/emu/machines/z88/Z88Machine.ts
- src/emu/machines/z88/memory/Z88UvEpromMemoryCard.ts
- test/z88/memory-eprom-io.test.ts
Bugfix in Z88Machine::doWritePort(): EPR register is B3h!
Test cases for 32K + 128K Eproms implemented.
Checked that OZ ROMs v4.0 and v4.7 can create File Cards when empty 32K or large UV Eproms are available in slot 3.
> Z88 UV Eprom emulation implemented

- src/common/machines/machine-registry.ts
Ive checked it with various ROM's ie. V4.0 UK gets 128K RAM, V3.25 DK gets 32K RAM, and OZ v5.0 gets 512K RAM in slot 0.
> Fixed default RAM for slot 0 for each machine type

- src/emu/machines/z88/Z88Machine.ts
The little detail slipped through. Now, IT KB is correctly selected, when selecting Z88 Italian legacy ROM.
> Fixed Z88 Italian KB not being part of supported list of layouts
